name: Refresh minty.txt

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  llminty:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Swift 6.1
        uses: slashmo/install-swift@v0.4.0
        with:
          version: "6.1"

      - name: Verify Swift
        run: swift --version

      - name: Build LLMinty
        run: swift build -c release

      - name: Generate minty.txt
        run: .build/release/llminty

      - name: Commit updated minty.txt (if changed)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: minty.txt
          commit_message: "chore: refresh minty.txt"
